# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-RBL
version:      1.02
version_from: RBL.pm
installdirs:  site
requires:
    Net::DNS:                      0
    NetAddr::IP:                   3.14
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
